<?php


namespace app\controller\api\service;


class UserProcess extends Process
{

    private $config;

    public function __construct($config, $imagePath, $image = null)
    {
        $this->config = $config;
        if (empty($this->config)) {
            return;
        }
        parent::__construct($this->config, $imagePath,$image);
    }

    public function run()
    {
        if (empty($this->config)) {
            return;
        }
        parent::run(); // TODO: Change the autogenerated stub
    }

}